-- migrate:up

CREATE TABLE public.users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    hashed_password TEXT
);

CREATE TABLE public.feed (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    url TEXT NOT NULL,
    type TEXT NOT NULL,
    user_id INTEGER NOT NULL REFERENCES public.users (id),
    UNIQUE (user_id, url, type)
);

CREATE TABLE public.item (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    feed_id INTEGER NOT NULL REFERENCES public.feed (id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    text TEXT NOT NULL,
    date TIMESTAMPTZ NOT NULL,
    link TEXT NOT NULL
);

CREATE TABLE public.feed_parser (
    feed_id INTEGER PRIMARY KEY REFERENCES public.feed (id) ON DELETE CASCADE,
    valid_for TIMESTAMPTZ NOT NULL
);

CREATE TABLE public.item_hash (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hash TEXT NOT NULL,
    feed_id INTEGER REFERENCES public.feed (id) ON DELETE CASCADE,
    UNIQUE (feed_id, hash)
);

CREATE TABLE public.webauthn_credentials (
    id BYTEA PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES public.users (id),
    credential TEXT NOT NULL,
    name TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_used_at TIMESTAMPTZ
);

CREATE TABLE public.refresh_tokens (
    id TEXT PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES public.users (id),
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- migrate:down
